-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 21:17:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical_clinic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medical_clinic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_clinic` DEFAULT CHARACTER SET utf8 ;
USE `medical_clinic` ;

-- -----------------------------------------------------
-- Table `medical_clinic`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`patients` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`patients` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pesel_encrypted` VARBINARY(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone_encrypted` VARBINARY(255) NULL,
  `address_encrypted` VARBINARY(255) NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`specializations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`specializations` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`specializations` (
  `specialization_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`specialization_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`doctors` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`doctors` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `specialization_id` INT NULL,
  PRIMARY KEY (`doctor_id`),
  INDEX `fk_doctors_specializations1_idx` (`specialization_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctors_specializations1`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `medical_clinic`.`specializations` (`specialization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`visits` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`visits` (
  `visit_id` INT NOT NULL AUTO_INCREMENT,
  `visit_date` DATETIME NULL,
  `patient_id` INT NULL,
  `doctor_id` INT NULL,
  `notes` TEXT NULL,
  `status` ENUM('Scheduled', 'Completed', 'Cancelled') NULL,
  PRIMARY KEY (`visit_id`),
  INDEX `fk_visits_patients1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_visits_doctors1_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `medical_clinic`.`patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_doctors1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `medical_clinic`.`doctors` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`diseases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`diseases` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`diseases` (
  `disease_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`disease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`medicines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`medicines` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`medicines` (
  `medicine_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`medicine_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`users` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password_hash` VARCHAR(255) NULL,
  `role` ENUM('ADMIN', 'RECEPTIONIST', 'DOCTOR', 'PATIENT') NULL,
  `patient_id` INT NULL,
  `doctor_id` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_users_patients1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_users_doctors1_idx` (`doctor_id` ASC) VISIBLE,
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE,
  UNIQUE INDEX `doctor_id_UNIQUE` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `medical_clinic`.`patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_doctors1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `medical_clinic`.`doctors` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`visits_has_diseases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`visits_has_diseases` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`visits_has_diseases` (
  `visits_visit_id` INT NOT NULL,
  `diseases_disease_id` INT NOT NULL,
  PRIMARY KEY (`visits_visit_id`, `diseases_disease_id`),
  INDEX `fk_visits_has_diseases_diseases1_idx` (`diseases_disease_id` ASC) VISIBLE,
  INDEX `fk_visits_has_diseases_visits1_idx` (`visits_visit_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_has_diseases_visits1`
    FOREIGN KEY (`visits_visit_id`)
    REFERENCES `medical_clinic`.`visits` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_has_diseases_diseases1`
    FOREIGN KEY (`diseases_disease_id`)
    REFERENCES `medical_clinic`.`diseases` (`disease_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_clinic`.`visits_has_medicines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`visits_has_medicines` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`visits_has_medicines` (
  `visits_visit_id` INT NOT NULL,
  `medicines_medicine_id` INT NOT NULL,
  PRIMARY KEY (`visits_visit_id`, `medicines_medicine_id`),
  INDEX `fk_visits_has_medicines_medicines1_idx` (`medicines_medicine_id` ASC) VISIBLE,
  INDEX `fk_visits_has_medicines_visits1_idx` (`visits_visit_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_has_medicines_visits1`
    FOREIGN KEY (`visits_visit_id`)
    REFERENCES `medical_clinic`.`visits` (`visit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_has_medicines_medicines1`
    FOREIGN KEY (`medicines_medicine_id`)
    REFERENCES `medical_clinic`.`medicines` (`medicine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
